#ifndef HEADER_SEMESTER_INCLUDED
#define HEADER_SEMESTER_INCLUDED

#include <string>
#include "../utils/vector.h"
#include "Date.h"

using namespace std;

struct Semester {
	/* OBJECT */
	int year;
	Date startDate, endDate;

	/* AUTOGENERATED WHEN ADDED */
	int auto_id;

	/* CONSTRUCTOR */
	Semester(): year(), startDate(), endDate(), auto_id(-1) {}
};

#endif
